-- CreateTable
CREATE TABLE "CaseRecord" (
    "id" TEXT NOT NULL,
    "patientName" TEXT,
    "age" TEXT,
    "sex" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "dueDate" TEXT,
    "bruxism" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "smileStyle" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "midline" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "estheticNotes" TEXT,
    "photos" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "scans" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "additionalNotes" TEXT,
    "caseType" TEXT,
    "toothType" TEXT,
    "finalShade" TEXT,
    "stumpShade" TEXT,
    "restorationTypes" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "materialOptions" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "restorationPrep" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "noted" TEXT,
    "contacts" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "occlusion" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "requiredScans" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "abutmentsLeft" TEXT,
    "abutmentsRight" TEXT,
    "ponticDesign" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "ponticContacts" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "ponticTeeth" TEXT,
    "bridgeMaterial" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "bridgeRequiredScans" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "implantBrand" TEXT,
    "implantPlatform" TEXT,
    "implantConnection" TEXT,
    "implantTooth" TEXT,
    "implantRestoration" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "implantEmergence" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "implantRequiredScans" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "implantAbutment" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "implantOcclusion" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "implantAllowed" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "fullArchDesign" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "fullArchFramework" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "fullArchVdo" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "fullArchOcc" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "fullArchToothSize" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "fullArchGingiva" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "fullArchMidline" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "fullArchRequiredScansTop" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "fullArchRequiredScans" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "digitalType" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "digitalArch" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "digitalVdo" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "digitalToothSetup" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "digitalShade" TEXT,
    "digitalBase" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "digitalCopy" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "digitalRequiredScans" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "digitalNewRecord" TEXT,
    "digitalChanges" TEXT,
    "partialType" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "partialFramework" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "partialMajorConnector" TEXT,
    "partialRests" TEXT,
    "partialShade" TEXT,
    "partialClasps" TEXT,
    "partialBaseAreas" TEXT,
    "partialAesthetics" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "partialRequiredScans" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "createdById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "CaseRecord_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "DentistProfile" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "licenseNumber" TEXT,
    "preferredContactMethod" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "specialty" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "assistantName" TEXT,
    "assistantPhone" TEXT,
    "officeManager" TEXT,
    "officeManagerPhone" TEXT,
    "whoApprovesDesigns" TEXT,
    "contactTimeWindow" TEXT,
    "standardOcclusalPreference" TEXT,
    "standardShadesUsed" TEXT,
    "clinicName" TEXT,
    "clinicPhone" TEXT,
    "clinicAddress" TEXT,
    "clinicState" TEXT,
    "clinicCity" TEXT,
    "zipcode" TEXT,
    "scannerType" TEXT,
    "preferredFileTransfer" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "DentistProfile_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "DentistProfile_userId_key" ON "DentistProfile"("userId");

-- AddForeignKey
ALTER TABLE "CaseRecord" ADD CONSTRAINT "CaseRecord_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DentistProfile" ADD CONSTRAINT "DentistProfile_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
